import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

export const leads = sqliteTable("leads", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  companyName: text("company_name").notNull(),
  contactName: text("contact_name"),
  contactTitle: text("contact_title"),
  phone: text("phone"),
  email: text("email"),
  alternativePhone: text("alternative_phone"),
  address: text("address"),
  city: text("city"),
  province: text("province"),
  postalCode: text("postal_code"),
  latitude: real("latitude"),
  longitude: real("longitude"),
  status: text("status", { enum: ["new", "contacted", "qualified", "unqualified", "converted"] }).notNull().default("new"),
  source: text("source", { enum: ["manual", "import", "referral", "website", "event"] }).default("manual"),
  qualification: text("qualification", { enum: ["hot", "warm", "cold"] }).default("cold"),
  segment: text("segment", { enum: ["enterprise", "smb", "government", "education", "other"] }).default("other"),
  industry: text("industry"),
  website: text("website"),
  notes: text("notes"),
  tags: text("tags").default("[]"),
  customFields: text("custom_fields").default("{}"),
  assignedTo: text("assigned_to"),
  territoryId: text("territory_id"),
  createdBy: text("created_by").notNull(),
  convertedDealId: text("converted_deal_id"),
  lastContactedAt: integer("last_contacted_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
});
