import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

export const visits = sqliteTable("visits", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  leadId: text("lead_id").notNull(),
  userId: text("user_id").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  visitType: text("visit_type", { enum: ["cold_call", "scheduled", "follow_up", "presentation", "closing"] }).notNull().default("scheduled"),
  status: text("status", { enum: ["planned", "checked_in", "in_progress", "completed", "cancelled", "no_show"] }).notNull().default("planned"),
  scheduledDate: text("scheduled_date").notNull(),
  scheduledStartTime: text("scheduled_start_time"),
  scheduledEndTime: text("scheduled_end_time"),
  checkinTime: integer("checkin_time", { mode: "timestamp" }),
  checkoutTime: integer("checkout_time", { mode: "timestamp" }),
  checkinLat: real("checkin_lat"),
  checkinLng: real("checkin_lng"),
  checkoutLat: real("checkout_lat"),
  checkoutLng: real("checkout_lng"),
  checkinDistanceMeters: real("checkin_distance_meters"),
  meetingNotes: text("meeting_notes"),
  nextSteps: text("next_steps"),
  dealId: text("deal_id"),
  routeStopId: text("route_stop_id"),
  durationMinutes: integer("duration_minutes"),
  isOfflineSync: integer("is_offline_sync", { mode: "boolean" }).default(false),
  syncConfirmedAt: integer("sync_confirmed_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
});
